"""empty message

Revision ID: 01a0db0b7e80
Revises: 89f9285e3dff
Create Date: 2025-11-28 22:54:38.447042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a0db0b7e80'
down_revision = '89f9285e3dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_color', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=15), nullable=False))

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('eye_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('skin_color')

    # ### end Alembic commands ###
